CREATE TABLE sagas_subcategories (
  id INTEGER(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  saga_id INTEGER(11) UNSIGNED NOT NULL,
  subcategory_id INTEGER(11) UNSIGNED NOT NULL,
  FOREIGN KEY (saga_id) REFERENCES sagas(id),
  FOREIGN KEY (subcategory_id) REFERENCES subcategories(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
