CREATE TABLE episodes (
  id INTEGER(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  number INTEGER(11) UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  duration_time INTEGER(11) UNSIGNED NOT NULL,
  episode_url VARCHAR (500) NOT NULL,
  saga_id INTEGER(11) UNSIGNED NOT NULL,
  season_id INTEGER(11) UNSIGNED,
  special_type_id INTEGER(11) UNSIGNED,
  FOREIGN KEY (saga_id) REFERENCES sagas(id),
  FOREIGN KEY (season_id) REFERENCES seasons(id),
  FOREIGN KEY (special_type_id) REFERENCES special_types(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
